name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 6.3.4
homepage: https://github.com/fluttercandies/extended_image

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  extended_image_library: ^3.4.1
  flutter:
    sdk: flutter
  meta: ^1.8.0
